#pragma once
#include "../../../firmware/src/stm32/mpconfigport.h"
#undef MICROPY_PY_TREZORDEFINITIONS
#define MICROPY_PY_TREZORDEFINITIONS (0)
#undef MICROPY_PY_TREZORPROTO
#define MICROPY_PY_TREZORPROTO (0)
#undef MICROPY_PY_TREZORTRANSLATE
#define MICROPY_PY_TREZORTRANSLATE (0)
#undef MICROPY_PY_TREZORUI
#define MICROPY_PY_TREZORUI (0)
#undef MICROPY_PY_TREZORUI_API
#define MICROPY_PY_TREZORUI_API (0)
#undef MICROPY_PY_TREZORUTILS
#define MICROPY_PY_TREZORUTILS (0)
