#include <assert.h>
#include <sec/authenticator.h>
#include <stdio.h>
#include <string.h>
#include "ecdsa.h"
#include "ed25519-donna/ed25519.h"
#include "nist256p1.h"
#include "sha2.h"
#include "test_backend.h"
#include "test_pin_protocol_host.h"

// Declared here rather than included, so that a missing implementation fails at
// link time instead of compiling against a header that promises one.
typedef auth_credential_public test_public;
extern bool auth_test_credential_work_zero(void);

static const uint8_t pin[16] = {1};
// version, hmac flag, UV_REQUIRED, RP length (BE), user/name lengths, fields
static const uint8_t metadata[] = {1,   1,   3,   0,   11,  1,   0,
                                   0,   0,   'e', 'x', 'a', 'm', 'p',
                                   'l', 'e', '.', 'c', 'o', 'm', 7};
static uint8_t rp[32];
static void expect_hex(const uint8_t *value, const char *hex, size_t len) {
  assert(strlen(hex) == len * 2);
  for (size_t i = 0; i < len; i++) {
    unsigned byte = 0;
    assert(sscanf(hex + 2 * i, "%2x", &byte) == 1 && value[i] == byte);
  }
}
static void unlock_permission(uint8_t permission, const uint8_t *bound_rp) {
  uint8_t key[65], peer[65], encrypted[48], scalar[32] = {0}, blob[16] = {0};
  size_t n;
  scalar[31] = 1;
  assert(ecdsa_get_public_key65(&nist256p1, scalar, peer) == 0);
  assert(auth_vault_key_agreement(key, 65) == AUTH_OK);
  // The vault takes the PIN hash encrypted under the shared secret, so the test
  // has to play the platform and encrypt it.
  pin_protocol_host_encrypt(scalar, key, 1, pin, 16, 0, blob);
  assert(auth_vault_issue_token(blob, sizeof(blob), 1, permission, bound_rp,
                                bound_rp ? 32 : 0, peer, 65, encrypted, 48,
                                &n) == AUTH_OK);
}
static void unlock(void) { unlock_permission(7, rp); }
static void setup(void) {
  auth_test_reset();
  sha256_Raw((const uint8_t *)"example.com", 11, rp);
  assert(auth_vault_init() == AUTH_OK);
  assert(auth_vault_provision(pin, 16) == AUTH_OK);
  unlock();
}
void test_authenticator_crypto(void) {
  test_public credential, opened;
  uint8_t signature[72], salts[64] = {0}, output[64], other[32] = {0};
  size_t n;
  for (int32_t algorithm = -7; algorithm >= -8; algorithm--) {
    setup();
    assert(auth_credential_create(rp, algorithm, metadata, sizeof(metadata),
                                  &credential) == AUTH_OK);
    assert(credential.id_len == sizeof(metadata) + 68);
    assert(memcmp(credential.id, "\xf1\xd0\x03\x00", 4) == 0);
    // Independently pinned Python hashlib/cryptography fixtures, with root
    // 01..20, seed 6d..8c, nonce 8d..98. Never generated by code under test.
    if (algorithm == -7) {
      expect_hex(credential.id,
                 "f1d003008d8e8f909192939495969798e0913f3a0ea5da87d30ce9e567e7c"
                 "01f4e0bd3eb41f24beb9c0ff71d15826576566a06cd655f436976d19b9b7a"
                 "fdb1fed6ca46c010af85fbba6a96a2f7928cebef7685920b9b1b280c",
                 89);
      expect_hex(
          credential.cose + 10,
          "03ac2697930bf73fb49cc4aa350ed4c42a44510ba1544680dbab8035e33b3662",
          32);
      expect_hex(
          credential.cose + 45,
          "054d966285460ea7ad5d809ec650c6e7ac1c4d7bb8df7c2c17131ac9619d3db7",
          32);
    } else {
      expect_hex(credential.id,
                 "f1d003008d8e8f909192939495969798e0913f3a0ea5da87d30ce9e567e7c"
                 "01f4e0bd3eb41f24beb9c0ff71d15826576596a06cd655f436976d19b9b7a"
                 "fdb1fed6ca46c010af85fbba90ff91849692ce2f50ecfb77563b73ae",
                 89);
      expect_hex(
          credential.cose + 10,
          "c6e96f8f5658c57c2a2142a083b2773821650e2c4f6b3f3aff3f643e8dc87c1f",
          32);
    }
    assert(auth_test_credential_work_zero());
    assert(auth_credential_open(credential.id, credential.id_len, rp,
                                &opened) == AUTH_OK);
    assert(opened.algorithm == algorithm);
    assert(opened.metadata_len == sizeof(metadata));
    assert(memcmp(opened.metadata, metadata, sizeof(metadata)) == 0);
    assert(memcmp(opened.cose, credential.cose, credential.cose_len) == 0);
    assert(auth_credential_sign(credential.id, credential.id_len, rp, algorithm,
                                (const uint8_t *)"message", 7, false, signature,
                                &n) == AUTH_OK);
    if (algorithm == -7) {
      uint8_t pub[65] = {4}, digest[32], raw[64];
      memcpy(pub + 1, credential.cose + 10, 32);
      memcpy(pub + 33, credential.cose + 45, 32);
      sha256_Raw((const uint8_t *)"message", 7, digest);
      assert(ecdsa_sig_from_der(signature, n, raw) == 0);
      assert(ecdsa_verify_digest(&nist256p1, pub, raw, digest) == 0);
    } else {
      assert(n == 64 && credential.cose_len == 42);
      assert(ed25519_sign_open((const uint8_t *)"message", 7,
                               credential.cose + 10, signature) == 0);
      expect_hex(
          signature,
          "0b6f53526d331a2c080b980756b51a6f17d9675b70bb2763c90fc0c81ab50a5f81a3"
          "b6f989b6db609d37410d70934b974bede7982db5236d7fc627e58fde4803",
          64);
    }
    assert(auth_credential_hmac_secret(credential.id, credential.id_len, rp,
                                       salts, 64, output) == AUTH_OK);
    assert(memcmp(output, output + 32, 32) == 0);
    expect_hex(
        output,
        "2e93ed8650123a1161cd17a8d8ade406759bf6bc832d90d324469d720313f44f", 32);
    assert(auth_test_credential_work_zero());
    assert(auth_resident_set(0, credential.id, credential.id_len, rp) ==
           AUTH_OK);
    assert(auth_resident_get(0, &opened) == AUTH_OK);
    assert(memcmp(credential.id, opened.id, credential.id_len) == 0);
    assert(auth_resident_set(1, credential.id, credential.id_len, rp) ==
           AUTH_DENIED);
    unlock();
    assert(auth_resident_delete(0) == AUTH_OK);
    assert(auth_resident_get(0, &opened) == AUTH_UNPROVISIONED);
    assert(auth_resident_get(100, &opened) == AUTH_INVALID_ARGUMENT);
    unlock();
    assert(auth_credential_open(credential.id, credential.id_len, other,
                                &opened) == AUTH_DENIED);
    assert(opened.id_len == 0 && auth_test_credential_work_zero());
    unlock();
    credential.id[credential.id_len - 1] ^= 1;
    assert(auth_credential_open(credential.id, credential.id_len, rp,
                                &opened) == AUTH_DENIED);
    assert(opened.id_len == 0 && auth_test_credential_work_zero());
    auth_vault_disconnect();
    assert(auth_test_transients_zero());
  }
  // Replacing a slot is also a mutation of its old RP, so a newly RP-bound
  // token must not overwrite another RP's existing discoverable credential.
  setup();
  assert(auth_credential_create(rp, -7, metadata, sizeof(metadata),
                                &credential) == AUTH_OK);
  assert(auth_resident_set(0, credential.id, credential.id_len, rp) == AUTH_OK);
  uint8_t alternative[sizeof(metadata)];
  memcpy(alternative, metadata, sizeof(metadata));
  alternative[9] = 'a';
  sha256_Raw(alternative + 9, 11, rp);
  unlock();
  assert(auth_credential_create(rp, -7, alternative, sizeof(alternative),
                                &opened) == AUTH_OK);
  assert(auth_resident_set(0, opened.id, opened.id_len, rp) == AUTH_DENIED);
  assert(auth_test_transients_zero() && auth_test_credential_work_zero());
  // Authentication failure must not release even public metadata. Flip every
  // envelope byte, including version, nonce, encrypted seed/metadata, and tag.
  setup();
  assert(auth_credential_create(rp, -7, metadata, sizeof(metadata),
                                &credential) == AUTH_OK);
  for (size_t i = 0; i < credential.id_len; i++) {
    unlock();
    credential.id[i] ^= 1;
    assert(auth_credential_open(credential.id, credential.id_len, rp,
                                &opened) != AUTH_OK);
    assert(opened.id_len == 0 && opened.metadata_len == 0 &&
           opened.cose_len == 0);
    assert(auth_test_transients_zero() && auth_test_credential_work_zero());
    credential.id[i] ^= 1;
  }
  // Wrong RP reaches the AEAD check under a token valid for that wrong RP.
  memcpy(other, rp, 32);
  memset(rp, 9, 32);
  unlock();
  assert(auth_credential_open(credential.id, credential.id_len, rp, &opened) ==
         AUTH_DENIED);
  assert(auth_test_transients_zero() && auth_test_credential_work_zero());
  memcpy(rp, other, 32);
  for (unsigned i = 0; i < 2; i++) {
    setup();
    auth_test_fail(i ? TEST_ZEROIZE : TEST_RNG);
    assert(auth_credential_create(rp, -7, metadata, sizeof(metadata),
                                  &opened) == AUTH_ERROR);
    assert(opened.id_len == 0 && auth_test_transients_zero() &&
           auth_test_credential_work_zero());
  }
  // TEST_ERASE is no longer in this list. Writing a resident record used to
  // take three storage calls -- invalidate the tag, write the record, write the
  // tag -- so an erase failure could break it. A record is now one snapshot
  // commit: the erase that happens inside it belongs to the replica manager,
  // below this backend, and has its own coverage in test_replica_records.c and
  // test_replica_power_cut.c. Erase failures are still asserted here, against
  // the operation that actually performs one.
  const auth_test_failure storage_failures[] = {TEST_READ, TEST_WRITE,
                                                TEST_INTERRUPTED};
  for (size_t i = 0; i < sizeof(storage_failures) / sizeof(storage_failures[0]);
       i++) {
    setup();
    assert(auth_credential_create(rp, -7, metadata, sizeof(metadata),
                                  &credential) == AUTH_OK);
    assert(auth_resident_set(0, credential.id, credential.id_len, rp) ==
           AUTH_OK);
    auth_test_fail(storage_failures[i]);
    assert(auth_resident_set(0, credential.id, credential.id_len, rp) ==
           AUTH_ERROR);
    assert(auth_test_transients_zero() && auth_test_credential_work_zero());
  }
  // Deleting a record is the operation that still erases, so an erase failure
  // must make it fail closed and leave nothing behind.
  setup();
  assert(auth_credential_create(rp, -7, metadata, sizeof(metadata),
                                &credential) == AUTH_OK);
  assert(auth_resident_set(0, credential.id, credential.id_len, rp) == AUTH_OK);
  auth_test_fail(TEST_ERASE);
  assert(auth_resident_delete(0) == AUTH_ERROR);
  assert(auth_test_transients_zero() && auth_test_credential_work_zero());
  setup();
  uint8_t no_hmac[sizeof(metadata)];
  memcpy(no_hmac, metadata, sizeof(metadata));
  no_hmac[1] = 0;
  assert(auth_credential_create(rp, -8, no_hmac, sizeof(no_hmac),
                                &credential) == AUTH_OK);
  assert(auth_credential_hmac_secret(credential.id, credential.id_len, rp,
                                     salts, 32, output) == AUTH_DENIED);
  for (size_t i = 0; i < 64; i++) assert(output[i] == 0);
  assert(auth_test_transients_zero() && auth_test_credential_work_zero());
  // Init/status alone, and a successful token carrying a different permission,
  // must not make cached root material usable for credential operations.
  setup();
  auth_vault_disconnect();
  assert(auth_vault_init() == AUTH_OK);
  assert(auth_vault_status().state == AUTH_OK);
  assert(auth_credential_create(rp, -7, metadata, sizeof(metadata), &opened) ==
         AUTH_DENIED);
  assert(auth_test_transients_zero());
  uint8_t public[65], peer[65], scalar[32] = {0}, ciphertext[48];
  scalar[31] = 1;
  assert(ecdsa_get_public_key65(&nist256p1, scalar, peer) == 0);
  assert(auth_vault_key_agreement(public, 65) == AUTH_OK);
  uint8_t hash_enc[16] = {0};
  pin_protocol_host_encrypt(scalar, public, 1, pin, 16, 0, hash_enc);
  assert(auth_vault_issue_token(hash_enc, sizeof(hash_enc), 1, 4, NULL, 0, peer,
                                65, ciphertext, 48, &n) == AUTH_OK);
  assert(auth_credential_open(credential.id, credential.id_len, rp, &opened) ==
         AUTH_DENIED);
  assert(auth_test_transients_zero() && auth_test_credential_work_zero());
  // Independent MC/GA/CM contracts in a mixed-RP resident store. These must
  // not pass only because a token combines all three permissions.
  setup();
  unlock_permission(1, rp);
  assert(auth_credential_create(rp, -7, metadata, sizeof(metadata),
                                &credential) == AUTH_OK);
  assert(auth_resident_set(0, credential.id, credential.id_len, rp) == AUTH_OK);
  uint8_t first_rp[32];
  memcpy(first_rp, rp, 32);
  sha256_Raw(alternative + 9, 11, rp);
  unlock_permission(1, rp);
  assert(auth_credential_create(rp, -8, alternative, sizeof(alternative),
                                &opened) == AUTH_OK);
  assert(auth_resident_set(1, opened.id, opened.id_len, rp) == AUTH_OK);
  assert(auth_resident_set(1, opened.id, opened.id_len, rp) == AUTH_DENIED);
  assert(auth_test_transients_zero());
  memcpy(rp, first_rp, 32);
  unlock_permission(2, rp);
  assert(auth_resident_get(1, &opened) == AUTH_UNPROVISIONED);
  assert(opened.id_len == 0);
  assert(auth_resident_get(0, &opened) == AUTH_OK);
  assert(auth_credential_sign(opened.id, opened.id_len, rp, -7,
                              (const uint8_t *)"message", 7, false, signature,
                              &n) == AUTH_OK);
  assert(auth_resident_delete(0) == AUTH_DENIED);
  assert(auth_test_transients_zero());
  unlock_permission(6, rp);
  assert(auth_resident_get(1, &opened) == AUTH_UNPROVISIONED);
  assert(auth_resident_get(0, &opened) == AUTH_OK);
  unlock_permission(4, NULL);
  assert(auth_resident_get(1, &opened) == AUTH_OK);
  assert(auth_resident_get(0, &credential) == AUTH_OK);
  assert(auth_resident_delete(1) == AUTH_OK);
  // A bound CM token still cannot replace another RP's occupied slot.
  sha256_Raw(alternative + 9, 11, rp);
  unlock_permission(4, rp);
  assert(auth_resident_delete(0) == AUTH_DENIED);
  unlock_permission(2, rp);
  assert(auth_resident_get(0, &opened) == AUTH_UNPROVISIONED);
  assert(auth_credential_open(credential.id, credential.id_len, rp, &opened) ==
         AUTH_DENIED);
  unlock_permission(4, NULL);
  assert(auth_resident_set(0, credential.id, credential.id_len, first_rp) ==
         AUTH_OK);
  assert(auth_resident_delete(0) == AUTH_OK);
  memcpy(rp, first_rp, 32);
  unlock_permission(1, rp);
  sha256_Raw(alternative + 9, 11, other);
  assert(auth_credential_create(other, -7, alternative, sizeof(alternative),
                                &opened) == AUTH_DENIED);
  assert(auth_test_transients_zero());
  for (uint8_t permission = 1; permission <= 2; permission++) {
    assert(auth_vault_key_agreement(public, 65) == AUTH_OK);
    // MakeCredential and GetAssertion permissions require an RP binding, and
    // that is refused on the arguments before anything is decrypted.
    assert(auth_vault_issue_token(hash_enc, sizeof(hash_enc), 1, permission,
                                  NULL, 0, peer, 65, ciphertext, 48,
                                  &n) == AUTH_INVALID_ARGUMENT);
    assert(auth_test_transients_zero());
  }
  puts("native authenticator credentials/crypto/residents: PASS");
}
